"use client"

import type React from "react"

import { useState } from "react"
import Link from "next/link"
import { ArrowLeft, Upload } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { uploadFaceImages } from "@/app/actions/upload-faces"

export default function UploadFacesPage() {
  const [facultyName, setFacultyName] = useState("")
  const [uploading, setUploading] = useState(false)
  const [result, setResult] = useState<{ success: boolean; message: string; basePath?: string } | null>(null)

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setUploading(true)
    setResult(null)

    const formData = new FormData(e.currentTarget)

    try {
      const response = await uploadFaceImages(formData)

      if (response.success) {
        setResult({
          success: true,
          message: `Successfully uploaded ${response.uploadedCount} images!`,
          basePath: response.basePath,
        })
        setFacultyName("")
        // Reset form
        ;(e.target as HTMLFormElement).reset()
      } else {
        setResult({
          success: false,
          message: response.error || "Upload failed",
        })
      }
    } catch (err) {
      setResult({
        success: false,
        message: `Error: ${(err as Error).message}`,
      })
    } finally {
      setUploading(false)
    }
  }

  return (
    <div className="flex min-h-screen flex-col">
      <header className="sticky top-0 z-50 w-full border-b bg-jefferson-deep-blue backdrop-blur-lg shadow-sm">
        <div className="container flex h-16 items-center justify-between">
          <Link href="/" className="flex items-center space-x-2">
            <span className="text-xl font-bold text-white">Center for Excellence in AI</span>
          </Link>
        </div>
      </header>

      <main className="flex-1 container py-12">
        <Link
          href="/team"
          className="inline-flex items-center mb-6 px-4 py-2 text-sm font-medium rounded-md border border-jefferson-deep-blue/20 hover:bg-jefferson-deep-blue/5 transition-colors"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Team
        </Link>

        <div className="max-w-2xl mx-auto">
          <h1 className="text-3xl font-bold mb-6">Upload Faculty Face Images</h1>
          <p className="text-gray-600 dark:text-gray-400 mb-8">
            Upload the face-looker generated images for a faculty member. These should be the grid of images showing
            different gaze directions (e.g., gaze_px0_py0_256.webp, gaze_px3_py3_256.webp, etc.)
          </p>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <Label htmlFor="faculty-name">Faculty Name (slug format)</Label>
              <Input
                id="faculty-name"
                name="facultyName"
                placeholder="e.g., dr-thomas, dr-vinogradskiy"
                value={facultyName}
                onChange={(e) => setFacultyName(e.target.value)}
                className="mt-2"
                required
              />
              <p className="text-sm text-gray-500 mt-1">
                Use lowercase with hyphens, this will be used in the file path
              </p>
            </div>

            <div>
              <Label htmlFor="face-files">Face Images (select all)</Label>
              <Input
                id="face-files"
                name="files"
                type="file"
                multiple
                accept="image/webp,image/png,image/jpeg"
                className="mt-2"
                required
              />
              <p className="text-sm text-gray-500 mt-1">
                Select all gaze images generated by face-looker (typically 121 .webp files)
              </p>
            </div>

            {result && (
              <div
                className={`p-4 rounded-md ${
                  result.success
                    ? "bg-green-50 dark:bg-green-900/20 text-green-600 dark:text-green-400"
                    : "bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400"
                }`}
              >
                <p className="font-medium mb-2">{result.message}</p>
                {result.basePath && (
                  <>
                    <p className="text-sm mt-2">Base path for FaceTracker component:</p>
                    <code className="block mt-2 p-2 bg-gray-100 dark:bg-gray-800 rounded text-sm">
                      {result.basePath}
                    </code>
                  </>
                )}
              </div>
            )}

            <Button type="submit" disabled={uploading} className="w-full">
              {uploading ? (
                <>
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2" />
                  Uploading...
                </>
              ) : (
                <>
                  <Upload className="mr-2 h-4 w-4" />
                  Upload Images
                </>
              )}
            </Button>
          </form>
        </div>
      </main>
    </div>
  )
}
